# تنظیمات Gradle — اپ اندروید سهند سرویس
org.gradle.jvmargs=-Xmx1280m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=false
# v2.11.1 — JDK با کامپایلر (سیستم فقط JRE دارد)
